"""Compile and run the Official SUSFS hooks generated by the real workflow."""
import ast
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import textwrap
import time
import unittest


WORKFLOW = Path(__file__).resolve().parents[2] / ".github/workflows/build.yml"


def c_function(source, name):
    start = re.search(rf"(?m)^int {name}\(", source).start()
    opening = source.index("{", start)
    depth = 1
    for end in range(opening + 1, len(source)):
        depth += (source[end] == "{") - (source[end] == "}")
        if depth == 0:
            return source[start:end + 1]
    raise AssertionError(name)


class OfficialExecSessionTests(unittest.TestCase):
    def generated_source(self, root):
        step = WORKFLOW.read_text(encoding="utf-8").split("- name: 修复 Official SUSFS 源码兼容", 1)[1]
        code = textwrap.dedent(step.split("python3 - <<'PY'\n", 1)[1].split("\n          PY", 1)[0])
        functions = [n for n in ast.parse(code).body if isinstance(n, ast.FunctionDef)]
        namespace = {"Path": Path, "re": re, "dedent": textwrap.dedent, "print": lambda *a: None}
        exec(compile(ast.Module(body=functions, type_ignores=[]), str(WORKFLOW), "exec"), namespace)
        path = root / "feature/sucompat.c"
        path.parent.mkdir()
        path.write_text(
            '#include <linux/printk.h>\n#include <linux/ptrace.h>\n'
            '#include "feature/sucompat.h"\n#include "sulog/event.h"\n'
            '#define SU_PATH "/system/bin/su"\n#define SH_PATH "/system/bin/sh"\n\n'
            '// sucompat: permitted process can execute \'su\' to gain root access.\n',
            encoding="utf-8",
        )
        patch = namespace["ensure_official_sucompat_execveat_compat"]
        self.assertTrue(patch(root))
        source = path.read_text(encoding="utf-8")
        self.assertFalse(patch(root))
        self.assertEqual(path.read_text(encoding="utf-8"), source)
        return source

    @unittest.skipUnless(shutil.which("cc"), "requires a C compiler")
    def test_only_successful_su_or_init_ksud_gets_a_descriptor(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = self.generated_source(root)
            hooks = "\n".join(c_function(source, name) for name in (
                "ksu_handle_execveat_init", "ksu_handle_execveat_sucompat",
                "ksu_handle_execveat", "ksu_handle_post_execveat_sucompat",
            ))
            stubs = r'''
#include <assert.h>
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#define __user
#define unlikely(x) (x)
#define likely(x) (x)
#define IS_ERR(x) ((uintptr_t)(x) >= (uintptr_t)-4095)
#define GFP_KERNEL 0
#define KSUD_PATH "/data/adb/ksud"
#define pr_info(...) ((void)0)
#define pr_err(...) ((void)0)
struct filename { const char *name; };
struct user_arg_ptr { int unused; };
struct ksu_sulog_pending_event { int unused; };
struct task { int pid; } task = {100}, *current = &task;
static const char su_path[] = "/system/bin/su", ksud_path[] = KSUD_PATH;
static bool init_domain, chrooted, bad_argv, umounted, early_handled;
static int profile_result, init_result, fd_count, profile_calls, pending_count;
static const char *get_user_arg_ptr(struct user_arg_ptr a, int n) { return bad_argv ? (void *)-EFAULT : "arg"; }
static void *get_current_cred(void) { return NULL; }
static bool is_init(void *c) { return init_domain; }
static bool current_chrooted(void) { return chrooted; }
static bool susfs_is_current_proc_umounted(void) { return umounted; }
static void susfs_set_current_proc_umounted(void) { umounted = true; }
static int escape_to_root_for_init(void) { return init_result; }
static int escape_with_root_profile(void) { profile_calls++; return profile_result; }
static struct ksu_sulog_pending_event *ksu_sulog_capture_sucompat(const char *n, struct user_arg_ptr *a, int g) { pending_count++; return (void *)1; }
static void ksu_sulog_emit_pending(struct ksu_sulog_pending_event *p, int r, int g) { pending_count--; }
static int ksu_install_su_fd(void) { return ++fd_count; }
static int ksu_handle_execveat_ksud(int *f, struct filename **p, void *a, void *e, int *g) { return early_handled; }
'''
            main = r'''
static void check(const char *name, int exec_ret, bool early, bool session, int expected_fd) {
    char buffer[128]; strcpy(buffer, name);
    struct filename f = {buffer}, *ptr = &f;
    struct user_arg_ptr args = {0}; int fd = 0, flags = 0;
    fd_count = profile_calls = pending_count = 0;
    int ret = early ? ksu_handle_execveat(&fd, &ptr, &args, &args, &flags)
        : ksu_handle_execveat_sucompat(&fd, &ptr, &args, &args, &flags);
    assert((ret == 0) == session);
    if (!ret) ksu_handle_post_execveat_sucompat(&fd, &ptr, &args, &args, &flags, &exec_ret);
    assert(fd_count == expected_fd);
    assert(pending_count == 0);
}
int main(void) {
    for (int early = 0; early < 2; early++) {
        init_domain = chrooted = bad_argv = early_handled = false;
        profile_result = 0;
        check("/system/bin/app_process64", 0, early, false, 0);
        check("/system/bin/init", 0, early, false, 0);
        check("/system/bin/su", 0, early, true, 1);
        check("/system/bin/su", -ENOENT, early, true, 0);
        profile_result = -EPERM;
        check("/system/bin/su", 0, early, false, 0);
        profile_result = 0; chrooted = true;
        check("/system/bin/su", 0, early, false, 0);
        chrooted = false; bad_argv = true;
        check("/system/bin/su", 0, early, false, 0);
        assert(profile_calls == 0);
        bad_argv = false; init_domain = true; umounted = false;
        check("/system/bin/app_process64", 0, early, false, 0);
        check("/system/bin/service", 0, early, false, 0);
        init_result = 0;
        check(KSUD_PATH, 0, early, true, 1);
        init_result = -EPERM;
        check(KSUD_PATH, 0, early, false, 0);
        init_result = 0; bad_argv = true;
        check(KSUD_PATH, 0, early, false, 0);
    }
    init_domain = false; early_handled = true;
    check("/system/bin/app_process64", 0, true, false, 0);
    struct filename f = {"/system/bin/app_process64"}, *ptr = &f;
    struct user_arg_ptr args = {0}; int fd = 0, flags = 0, retval = 0;
    fd_count = 0;
    ksu_handle_post_execveat_sucompat(&fd, &ptr, &args, &args, &flags, &retval);
    assert(fd_count == 0); /* Defense against stale callers. */
    assert(ksu_handle_execveat_sucompat(&fd, NULL, &args, &args, &flags) != 0);
    ptr = NULL;
    assert(ksu_handle_execveat_sucompat(&fd, &ptr, &args, &args, &flags) != 0);
    ksu_handle_post_execveat_sucompat(&fd, &ptr, &args, &args, &flags, &retval);
    ptr = &f; f.name = NULL;
    assert(ksu_handle_execveat_sucompat(&fd, &ptr, &args, &args, &flags) != 0);
    ksu_handle_post_execveat_sucompat(&fd, &ptr, &args, &args, &flags, &retval);
    ptr = (void *)-EINVAL;
    assert(ksu_handle_execveat_sucompat(&fd, &ptr, &args, &args, &flags) != 0);
    ksu_handle_post_execveat_sucompat(&fd, &ptr, &args, &args, &flags, &retval);
    ptr = &f;
    ksu_handle_post_execveat_sucompat(&fd, &ptr, &args, &args, &flags, NULL);
    assert(fd_count == 0);
    return 0;
}
'''
            c_path = root / "hooks.c"
            binary = root / ("hooks.exe" if os.name == "nt" else "hooks")
            c_path.write_text(stubs + hooks + main, encoding="utf-8")
            result = subprocess.run([shutil.which("cc"), "-std=gnu11", str(c_path), "-o", str(binary)], capture_output=True, text=True, encoding="utf-8", errors="replace")
            self.assertEqual(result.returncode, 0, result.stderr)
            try:
                result = subprocess.run([str(binary)], capture_output=True, text=True, encoding="utf-8", errors="replace")
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            finally:
                for attempt in range(50):
                    try:
                        binary.unlink(missing_ok=True)
                        break
                    except PermissionError:
                        if os.name != "nt" or attempt == 49:
                            raise
                        time.sleep(0.1)
